### ISSUE TITLE
[BUG] Locomotion breaks when used with Ice Skate system

### ISSUE THREAD

**Issue by atomiklan** [Mattshark89/OpenFlight-VRC#123]
**Describe the bug**
Most likely similar to the swim system issue from a year of so ago, when using the latest version of Open flight in conjunction with the Ice Skating Udon system, locomotion breaks in the same way.

**To Reproduce**
1. Take flight
2. Land on the ice rink
3. Upon exiting rink, locomotion will fail. Must rejoin to fix. 

**Expected behavior**
Locomotion good :)

**Screenshots**
See attached video

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VRC SDK Version: 3.7.4
 - UdonSharp: Latest for SDK       

**Additional context**
https://jokerispunk.booth.pm/items/4410848
https://vrch.at/kp3qzp5t

https://github.com/user-attachments/assets/3fc97e74-a883-48a6-9d8e-5bf585aa3067

**Comment by Happyrobot33** [comment]
I cant find where to edit the issue template right now, but I need to edit it to ask, what version of openflight is the world on? in theory, this should have been fixed when the dynamic physics toggle was added

**Comment by Happyrobot33** [comment]
nvm lol noticed you mentioned latest version. Is this toggle enabled or disabled in the world upload?

https://github.com/Mattshark89/OpenFlight-VRC/blob/7cd0a4b89de876538fd87132722b4d7e8cb214fd/Packages/com.mattshark.openflight/Runtime/Scripts/Flight/WingFlightPlusGlide.cs#L179-L183

**Comment by Happyrobot33** [comment]
> Heading to bed soon, but will check back in with this tonight. Thanks for the help! If you guys are able to find a work around that would be amazing. Trying to get this world setup in time for the big xmas party at end of year.

So I downloaded the ice skating prefab. You will want to call Land() in the enable method in Skating.cs

```cs
// cache playercontroller values for later reversion and set to 0
//  needed to prevent non-fbt users from moving during IK immobilization pause
<----- Add land here
walkCache = lp.GetJumpImpulse();
strafeCache = lp.GetStrafeSpeed();
runCache = lp.GetRunSpeed();
jumpCache = lp.GetJumpImpulse();
lp.SetWalkSpeed(0f);
lp.SetStrafeSpeed(0f);
lp.SetRunSpeed(0f);
lp.SetJumpImpulse(0f);
```

**Comment by Happyrobot33** [comment]
> Could you show what I am specifically adding to skate.cs please? Sorry, I am not fluent in C#.

add `using OpenFlightVRC;` to the top of the file

add `public WingFlightPlusGlide wingFlightPlusGlide;` below
```cs
public class Skating : BaseIceSkatingUdon
    {
```

then do `wingFlightPlusGlide.Land();` where i pointed out before. Then in your scene youll need to fill in the wingFlightPlusGlide slot in the inspector

**Comment by Happyrobot33** [comment]
Just checking in, is this resolved in your project? I wish there was a more integrated way for me to solve this that doesnt involve editing c# scripts of other packages but it doesnt seem like there is
