### ISSUE TITLE
[BUG] Infinite acceleration with main menu open

### ISSUE THREAD

**Issue by madkat** [Mattshark89/OpenFlight-VRC#20]
Swinging arms with enough force to cause lift, while the main menu is open, results in extreme amounts of acceleration. This results in extreme disorientation and loss of player control.

A second flap may be required. Reproduction is consistent.

**Comment by madkat** [comment]
Going to try an existing mechanism for detecting menu open to cancel takeoff. [Found here](https://github.com/Superbstingray/UdonPlayerPlatformHook/blob/main/UdonPlatformHook/Scripts/UdonPlatformHook.cs#L128)

**Comment by Mattshark89** [comment]
Good catch! Will have a look at this issue and the proposed solution

**Comment by madkat** [comment]
It seems likely that there should be a way to determine the menu is open based on a lack of player movement between ticks. Or possibly a more elegant way to utilize the menu detection to not only prevent takeoff but also freeze flight until they resume. I went with a solution that has the least impact on existing code given that it touches the core flight system.

**Comment by Mattshark89** [comment]
The helper function `Land()` is designed to disable flight entirely. Modifying this `if` statement to also trigger if the menu is open might be the best way to avoid similar issues in the future: https://github.com/Mattshark89/OpenFlight-VRC/blob/572d381e54a8f74fcf9f948c26c504e5422880a4/Packages/com.mattshark.openflight/Runtime/Scripts/Flight/WingFlightPlusGlide.cs#L371

**Comment by Mattshark89** [comment]
The lack-of-player-movement idea may work as well. I'd like to do some testing of that

**Comment by madkat** [comment]
I think there would be a side-effect to moving to `Land()`. If a player is mid flight and opens the menu then they would unceremoniously plummet rather than continuing to glide.

**Comment by Mattshark89** [comment]
I thought about that too, but I don't think many people would want to try and navigate their large menu while flying anyways. I'd assume most people would try to land first.

I'm also suggesting Land() to avoid potential issues in the future with other features; will you maintain your speed if you open your menu while gliding at an upwards angle? Once wind zones are added, will that multiply your momentum upwards? Etc.

**Comment by madkat** [comment]
All very good points. I'll move the implementation and do some testing.

**Comment by Mattshark89** [comment]
Thanks! Let me know if you want any help with testing etc.. This bug is a good find

**Comment by madkat** [comment]
Initial tests look good so I've updated the PR. Even having the flight canceled is not too jarring. Do you have a "standard" set of actions for testing that flight is operating the way that you expect?

**Comment by Mattshark89** [comment]
No standard testing procedures. I'll goof around with these changes tomorrow and will do the merge if it all checks out
