### ISSUE TITLE
[FEATURE] UI Styler for UI to persist color changes after updates

### ISSUE THREAD

**Issue by mackandelius** [Mattshark89/OpenFlight-VRC#28]
Since any change of color to the tablet resets after an update to OpenFlight, it would good to have a similar sort of thing to what USharpVideo uses to style their video player, except in this case it would be excluded from the prefab and would probably need to be a script the world creator attaches to a non-OpenFlight-prefab game object themselves, as a I assume that is the only way to persist data.

https://github.com/MerlinVR/USharpVideo/wiki/ui-styles

With credit there doesn't seem to be any reason why the script USharpVideo is using couldn't be reused here, it is very modular, would just really need the main "Styler" component modified for the OpenFlight tablet (just a reduction in number of color fields) and the "style markup" components pre-configured for each part of the tablet in the prefab.

**Comment by Happyrobot33** [comment]
Persisent data is actually possible using editorprefs, and we are actually already storing persistent data in the Extensions-Preview branch for if you have OpenFlight zone gizmos shown

**Comment by Happyrobot33** [comment]
Implementation live in [OpenFlight-1.4.0-beta.1](https://github.com/Mattshark89/OpenFlight-VRC/releases/tag/OpenFlight-1.4.0-beta.1)
