### ISSUE TITLE
Debug weight toggle [BUG]

### ISSUE THREAD

**Issue by Douie2020** [Mattshark89/OpenFlight-VRC#30]
**Describe the bug**
Setting the weight to max in the debug menu and then flapping really hard made me respawn and be stuck in place. Once in place I could no longer hear anyone nor could they hear me, and movement was flipped as well. So if I looked left my avatar would instead look right and the same happened if I did the opposite, this was the same if I looked either up or down was well, or when turning on the spot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Set Flap Strength to max (800), Flight gravity to min (0.0), Glide control to max (4), and Air friction to min (0).
3. Then go to 'Debug'
4. Set weight to min (or max but I am sure I did min)
5. Flap arms to take off

**Expected behaviour**
I expected myself to shoot very fast up into the air and very high up very quickly.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - VRC SDK Version: latest
 - UdonSharp Version: latest (I have no idea)

**Additional context**

**Comment by Happyrobot33** [comment]
This raises a fair point that we need to lower limit alot of the sliders
