### ISSUE TITLE
[BUG] Some avatar seats will trigger a flap

### ISSUE THREAD

**Issue by Happyrobot33** [Mattshark89/OpenFlight-VRC#34]
**Describe the bug**
Upon exiting certain configurations of avatar seats, the player will be punted upward like they started flapping. This only occurs when require jump is disabled

**To Reproduce**
Have not found a avatar to reproduce this as of yet

**Expected behavior**
This to not happen

**Additional context**
This problem was on furry hideout, which notably is know to currently have a outdated version of OpenFlight before the new glide detection and before the menu freeze bug. Unsure if this matters as of the filing of this bug

**Comment by Mattshark89** [comment]
The cause has been found: velocity is added upon flapping inside a seat, and it is never reset to zero, something I assumed VRC's physics engine would handle.
Example: flap once, your Y speed becomes 7 and freezes. Flap again, it becomes 14. 21, 28, 35, etc... once you get out of the seat, enjoy your flight

**Comment by Mattshark89** [comment]
Solved:  https://vrchat.com/home/launch?worldId=wrld_ef75dcc8-02fa-43ef-8f42-7b8159783d3d
