### ISSUE TITLE
[FEATURE] Optional flight sound and visual effects

### ISSUE THREAD

**Issue by MaleusDragon** [Mattshark89/OpenFlight-VRC#38]
Not sure how difficult this would be, but I feel like it could add a ton to the experience. No worries if there is no interest.

**Describe the solution you'd like**
Optional Audio feedback for flight for example;
- you can hear the air rushing past and have the sound change depending on velocity
- slight air resistance sound effects for successful wing flaps, and braking

**Comment by Mattshark89** [comment]
Noted. Will keep this request open

**Comment by Mattshark89** [comment]
May as well mention I've been wanting to do something like this for a while, but haven't because I have no audio manipulation experience. I'd try and make the wind louder the faster you travel, etc.. Would love to try it in the future though, or see how others have done it in other instances.

**Comment by Happyrobot33** [comment]
so, this is going to be interesting to implement

Networking on this platform just..... sucks

I am looking into it though

**Comment by Happyrobot33** [comment]
using https://github.com/CyanLaser/CyanPlayerObjectPool I have managed to get per-player information sync working
![image](https://github.com/Mattshark89/OpenFlight-VRC/assets/32679887/7fd25567-02ad-4ba2-bfa1-b3d732052457)
This means I can properly work on the effects implementation now

**Comment by Happyrobot33** [comment]
just an update, pretty far deep into the implementation stages of this, pretty much borderline release candidate at this point, it just needs more testing

**Comment by Happyrobot33** [comment]
Finally merged! Release is [1.6.0](https://github.com/Mattshark89/OpenFlight-VRC/releases/tag/OpenFlight-1.6.0)
