### ISSUE TITLE
[DOCS] Video not playing on Firefox

### ISSUE THREAD

**Issue by nponsard** [Mattshark89/OpenFlight-VRC#98]
When browsing to https://mattshark89.github.io/OpenFlight-VRC/docs/#/Themes with Firefox 127.0 on windows and linux the first video in the page doesn't load due to an unsupported format (see attached screenshot).

This affects only the `/OpenFlight-VRC/docs/Images/UI%20Styler/Demo/Loop.mp4` video file, it seems to be a problem with the encoding/file name (Matroska data in a .mp4) 

![image](https://github.com/Mattshark89/OpenFlight-VRC/assets/56651588/cbf8ff64-c15a-44a2-b7d9-81d46ffb50d4)

**Comment by Happyrobot33** [comment]
somehow, this issue slipped me recognizing it exists. Looking into it now :)
